clearvars
close all
clc

repoRoot = fileparts(mfilename('fullpath'));
if isempty(repoRoot)
    repoRoot = pwd;
end

addpath(fullfile(repoRoot, 'src'));

cfg = defaultConfig(repoRoot);
dataset = loadDataset(cfg.dataFile);

strategies = repmat(struct( ...
    'name', "", ...
    'description', "", ...
    'defaultChannel', "", ...
    'alphaPreferences', {{}}, ...
    'sameChannelControl', false), 2, 1);

strategies(1).name = "primary";
strategies(1).description = "Delta/theta/beta from F4C4; alpha from posterior channel when available.";
strategies(1).defaultChannel = "F4C4";
strategies(1).alphaPreferences = {'P3O1', 'P4O2', 'F4C4'};
strategies(1).sameChannelControl = false;

strategies(2).name = "same_channel_control";
strategies(2).description = "All bands extracted from F4C4 as a same-channel control.";
strategies(2).defaultChannel = "F4C4";
strategies(2).alphaPreferences = {'F4C4'};
strategies(2).sameChannelControl = true;

results = cell(numel(strategies), 1);
for idx = 1:numel(strategies)
    results{idx} = analyzeStrategy(dataset, cfg, strategies(idx));
end
results = vertcat(results{:});

primaryTable = results(1).summaryTable;
controlTable = results(2).summaryTable;

comparisonTable = table( ...
    primaryTable.Band, ...
    primaryTable.EEG_Channel, ...
    primaryTable.MeanCoherence, ...
    primaryTable.PeakCoherence, ...
    primaryTable.PeakFreq_Hz, ...
    primaryTable.AUC_Coherence, ...
    controlTable.EEG_Channel, ...
    controlTable.MeanCoherence, ...
    controlTable.PeakCoherence, ...
    controlTable.PeakFreq_Hz, ...
    controlTable.AUC_Coherence, ...
    primaryTable.MeanCoherence - controlTable.MeanCoherence, ...
    primaryTable.PeakCoherence - controlTable.PeakCoherence, ...
    primaryTable.AUC_Coherence - controlTable.AUC_Coherence, ...
    'VariableNames', { ...
        'Band', ...
        'Primary_Channel', ...
        'Primary_MeanCoherence', ...
        'Primary_PeakCoherence', ...
        'Primary_PeakFreq_Hz', ...
        'Primary_AUC_Coherence', ...
        'Control_Channel', ...
        'Control_MeanCoherence', ...
        'Control_PeakCoherence', ...
        'Control_PeakFreq_Hz', ...
        'Control_AUC_Coherence', ...
        'Delta_MeanCoherence_PrimaryMinusControl', ...
        'Delta_PeakCoherence_PrimaryMinusControl', ...
        'Delta_AUC_PrimaryMinusControl'});

exportProjectOutputs(dataset, results, comparisonTable, cfg);

save(fullfile(cfg.resultsDir, 'analysis_outputs.mat'), ...
    'cfg', 'dataset', 'results', 'comparisonTable');

writetable(primaryTable, fullfile(cfg.resultsDir, 'summary_primary.csv'));
writetable(controlTable, fullfile(cfg.resultsDir, 'summary_same_channel_control.csv'));
writetable(comparisonTable, fullfile(cfg.resultsDir, 'strategy_comparison.csv'));

[~, idxPrimary] = max(primaryTable.MeanCoherence);
[~, idxControl] = max(controlTable.MeanCoherence);

fprintf('\n');
fprintf('Analysis complete.\n');
fprintf('Primary strategy strongest mean coherence: %s (%s), mean = %.4f, peak = %.4f at %.4f Hz\n', ...
    primaryTable.Band(idxPrimary), ...
    primaryTable.EEG_Channel(idxPrimary), ...
    primaryTable.MeanCoherence(idxPrimary), ...
    primaryTable.PeakCoherence(idxPrimary), ...
    primaryTable.PeakFreq_Hz(idxPrimary));
fprintf('Same-channel control strongest mean coherence: %s (%s), mean = %.4f, peak = %.4f at %.4f Hz\n', ...
    controlTable.Band(idxControl), ...
    controlTable.EEG_Channel(idxControl), ...
    controlTable.MeanCoherence(idxControl), ...
    controlTable.PeakCoherence(idxControl), ...
    controlTable.PeakFreq_Hz(idxControl));
fprintf('Saved figures to: %s\n', cfg.figuresDir);
fprintf('Saved tables and MAT outputs to: %s\n\n', cfg.resultsDir);
